repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8  # Use the same version as installed via poetry
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix, --select, ALL]
    -   id: ruff-format
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0 # Use the same version as installed via poetry
    hooks:
    -   id: black
        args: [--check]
